### PR TITLE
Remove spyware

### PR DESCRIPTION
**Pull request by ddevault**
Libraries should not spy on people.

**Libraries should not spy on people.**

### CODE REVIEW

**Comment by misteroneill** [comment]
Thanks for the PR, but we can't accept it.

You can opt out of the tracking pixel that comes with the CDN version of Video.js using:

```js
window.HELP_IMPROVE_VIDEOJS = false;
```

This was previously documented, but we accidentally lost it a few months ago in a rewrite of the setup guide. I've opened [a PR](https://github.com/videojs/videojs.com/pull/65) to address that oversight.

Alternatively, you can use the version of Video.js on npm - it does not include the tracking pixel.

**Comment by ddevault** [comment]
Bullshit. You **can** remove it.

DO NOT SPY ON YOUR USERS.

**Comment by ddevault** [comment]
When was the last time you did anything with the data other than masturbate over it?

**Comment by misteroneill** [comment]
Your attitude and behavior are totally unacceptable and immature. I'm locking this thread.

**Pull request closed without merging**
